SELECT INS.NAME, INS.DATETIME FROM ANIMAL_INS AS INS
    LEFT JOIN ANIMAL_OUTS AS OUTS
    ON INS.ANIMAL_ID = OUTS.ANIMAL_ID
    WHERE INS.NAME IS NOT NULL AND OUTS.NAME IS NULL
    ORDER BY INS.DATETIME
    LIMIT 3;